### ISSUE TITLE
Issue installing gcloud using command "npm install --save gcloud"

### ISSUE THREAD

**Issue by paryasomayajulu** [Voxer/sse4_crc32#39] opened 2015-08-22 14:23 UTC
HI,
I have an issue installing gcloud package on my machine . I am getting following error. So could you please help me out with this.
----------------------------------------------------------------------------------------------------

F:\Projects\Kiran\Bald-Eagle\mcapi>npm install --save gcloud
npm WARN package.json mc-api@1.0.0 No README data
npm WARN package.json mc-api@1.0.0 No license field.
-

> sse4_crc32@3.4.0 install F:\Projects\Kiran\Bald-Eagle\mcapi\node_modules\gclou
d\node_modules\sse4_crc32
> node-gyp rebuild

F:\Projects\Kiran\Bald-Eagle\mcapi\node_modules\gcloud\node_modules\sse4_crc32>i
f not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\np
 else (node  rebuild ) ..\node_modules\node-gyp\bin\node-gyp.js" rebuild \)
configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:114:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Projects\Kiran\Bald-Eagle\mcapi\node_modules\gcloud\node_modules
\sse4_crc32
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "gcloud"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sse4_crc32@3.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sse4_crc32@3.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sse4_crc32 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sse4_crc32
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Projects\Kiran\Bald-Eagle\mcapi\npm-debug.log

**Comment by anandsuresh** [comment] 2015-08-22 17:06
@paryasomayajulu Can you please try cloning the sse4_crc32 repo, building it (`make clean; make`) and running `npm run-script debug` and paste the response here?

Also, what platform are you running on?

**Comment by ivan** [comment] 2015-08-22 18:45
The relevant part is the

```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

You need Python 2.7 and Visual Studio 2013 (or 2015?) installed to build native addons on Windows.

**Comment by ivan** [comment] 2015-08-22 18:49
You say in https://github.com/GoogleCloudPlatform/gcloud-node/issues/817 that "Python thing is that i regularly get and i am ignoring it since past.".  If you ignored it in the past without consequence, it was probably because a native addon was optional.  I'm guessing sse4_crc32 is not optional for gcloud-node, so you need Python and VS2013.

**Comment by anandsuresh** [comment] 2015-08-22 19:30
I'd second @ivan's advice. If you have in fact never built any native addons in the past, then that might explain how you got through without any issues. SSE4_CRC32 uses node-gyp to build the native add-on and requires python to be installed.

**Comment by gkorland** [comment] 2015-08-31 21:12
Is there a way to fallback to software based implementation if the hardware based can't be built?

**Comment by anandsuresh** [comment] 2015-08-31 21:19
@gkorland The software is designed to use the best possible implementation that works. So it should, at runtime, pick the best variant (H/w or S/w).

**Comment by gkorland** [comment] 2015-08-31 21:45
@anandsuresh the problem is that I'm trying to deploy the app on a PaaS that doesn't allow the build process to run.

**Comment by anandsuresh** [comment] 2015-08-31 21:47
That might be hard. Not sure how you'd plan on installing the module without building it! :( Perhaps if you could give me more information, I might be able to make some suggestions.

**Comment by gkorland** [comment] 2015-08-31 21:51
It's pretty simple I'm using gcloud which in turn uses ss4_crc32.
My node app server is deployed on Azure Web App which doesn't have VSbuild.
So,I'm getting " error MSB3428: Could not load the Visual C++ component "VCBuild.exe"

**Comment by anandsuresh** [comment] 2015-08-31 21:54
So the issue here is that both the hardware and software implementations are in C and need to be compiled to be used. Perhaps you can build the component offline and check it into the repository. Not the best way to deal with it, but lacking a build environment, you might need to get creative.

**Comment by anandsuresh** [comment] 2015-08-31 22:03
@paryasomayajulu I'm closing this issue for now. Feel free to reopen it if you are still facing problems.

**Closed by anandsuresh** 2015-08-31 22:03 UTC

**Comment by Jeff-Mikkelson** [comment] 2018-01-23 19:45
This is killing the Google Cloud Storage Node.js Client inside of Windows 10: https://github.com/googleapis/nodejs-storage

Per Google Cloud Storage instructions above, 
1) I run npm install --save @google-cloud/storage
2) I try run the sample code but module.js reports "c:\......\node_modules\sse4_crc32\build\sse4_crc32.node" is not found
3) I run npm install sse4_crc32 --save and gyp reports Error: Can't find Python executable "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython", you can set the PYTHON env variable.
4) I type "set" from the command prompt which reports PYTHON=C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython    
5) I do a dir on the directory above and I can see python.exe.   
6) I set PYTHON as a user environment variable, reboot, go back to step 3 and get the same error.
