### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by swilly22** [Voxer/sse4_crc32#45] opened 2015-09-16 17:57 UTC
roilipman:sse4_crc32 roilipmangmailcom$ make
./node_modules/.bin/node-gyp clean
make: ./node_modules/.bin/node-gyp: No such file or directory
make: [clean] Error 1 (ignored)
npm install .
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine hoek@2.16.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
|
> sse4_crc32@4.1.0 install /Users/roilipmangmailcom/Dev/sse4_crc32
> node-gyp rebuild

  CXX(target) Release/obj.target/crc32c_sse42/src/crc32c_sse42.o
  LIBTOOL-STATIC Release/crc32c_sse42.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make[1]: *** [Release/crc32c_sse42.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/roilipmangmailcom/Dev/sse4_crc32
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! sse4_crc32@4.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sse4_crc32@4.1.0 install script.
npm ERR! This is most likely a problem with the sse4_crc32 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sse4_crc32
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "."
npm ERR! cwd /Users/roilipmangmailcom/Dev/sse4_crc32
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/roilipmangmailcom/Dev/sse4_crc32/npm-debug.log
npm ERR! not ok code 0
make: *** [configure] Error 1

**Comment by anandsuresh** [comment] 2015-09-16 18:01
What platform and compiler versions are you using?

**Comment by swilly22** [comment] 2015-09-16 18:05
mac,
./node_modules/.bin/node-gyp --version v2.0.2

**Comment by anandsuresh** [comment] 2015-09-16 18:05
What about gcc/clang?

**Comment by swilly22** [comment] 2015-09-16 18:09
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by anandsuresh** [comment] 2015-09-16 18:12
Also what do you get for running `libtool -h`

**Comment by anandsuresh** [comment] 2015-09-16 18:14
Also, do you have the full XCode system installed or just the command line tools?

**Comment by swilly22** [comment] 2015-09-16 18:18
libtool -h
error: libtool: unknown option character `h' in: -h
Usage: libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]

I believe i've got the full XCode system installed.

**Comment by anandsuresh** [comment] 2015-09-16 18:20
Lastly, please try running `ls -la $(which libtool)`. It should be pointed to `/usr/bin/libtool`, unless you have installed something that pointed it to a different version of libtool. The issue is that the version of libtool on the $PATH doesn't support the `-static` flag.

**Comment by swilly22** [comment] 2015-09-16 18:26
ls -la $(which libtool)
-r-xr-xr-x  1 root  admin  174140 Jan 11  2015 /opt/local/bin/libtool

Thank you!

**Comment by anandsuresh** [comment] 2015-09-16 18:28
That's the culprit. That version probably doesn't support the `-static` flag.

You might want to switch that over to use `/usr/bin/libtool` and the world should be good again.

I'm going to close this now. Please feel free to re-open if the issue persists.

**Closed by anandsuresh** 2015-09-16 18:28 UTC
